# Generated by Django 5.2.17 on 2026-09-16 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('dr_code', models.CharField(blank=True, help_text='Distribution Representative code, e.g. SGD_SGD_DR01. Only set for DR users.', max_length=20)),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, help_text='Field hierarchy: DR -> FSO -> Distribution Manager (an FSO supervises up to ~7 DRs).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='accounts.userprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, help_text='Branch/warehouse this user is restricted to. Blank = all branches (Owner/HQ roles).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='warehouses.warehouse')),
            ],
        ),
    ]
