# Generated by Django 5.2.17 on 2026-09-16 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('channel_type', models.CharField(choices=[('DD', 'DD - Urban Retail (Direct Delivery)'), ('VDD', 'VDD - Rural Retail (Village Direct Delivery)'), ('WS', 'WS - Urban Wholesale'), ('VWS', 'VWS - Rural Wholesale'), ('MANDI', 'MANDI - Mandi Wholesale')], max_length=10)),
                ('filer_status', models.CharField(choices=[('FILER', 'Filer'), ('NON_FILER', 'Non-Filer')], default='NON_FILER', max_length=10)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DORMANT', 'Dormant'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10)),
                ('opened_on', models.DateField(default=django.utils.timezone.now)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel_type', 'name'],
                'unique_together': {('name', 'channel_type', 'filer_status')},
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Internal SKU code, e.g. DNH-20HL', max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('variant', models.CharField(blank=True, help_text='e.g. Lights, Swiss, Regular', max_length=100)),
                ('pack_size', models.CharField(help_text='e.g. 20 HL, 10 HL, LEP', max_length=20)),
                ('sticks_per_pack', models.PositiveIntegerField(default=20)),
                ('barcode', models.CharField(blank=True, max_length=64)),
                ('current_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCONTINUED', 'Discontinued')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skus', to='catalog.brand')),
            ],
            options={
                'verbose_name': 'SKU',
                'verbose_name_plural': 'SKUs',
                'ordering': ['brand__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CostPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_history', to='catalog.sku')),
            ],
            options={
                'verbose_name_plural': 'Cost price history',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='ChannelPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_from', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.channel')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_prices', to='catalog.sku')),
            ],
            options={
                'verbose_name_plural': 'Channel prices',
                'ordering': ['-effective_from'],
                'unique_together': {('channel', 'sku', 'effective_from')},
            },
        ),
    ]
