# Generated by Django 5.2.17 on 2026-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderline',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Optional — needed for batch-tracked SKUs like VELO (questionnaire #18).', max_length=50),
        ),
        migrations.AddField(
            model_name='purchaseorderline',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Optional — needed for batch-tracked SKUs like VELO.', null=True),
        ),
    ]
