# Generated by Django 5.2.17 on 2026-09-28 11:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('VOUCHER', 'Voucher'), ('PURCHASE', 'Purchase order received'), ('PURCHASE_RETURN', 'Purchase return'), ('SALE', 'Sales order confirmed'), ('SALE_RETURN', 'Sales return'), ('PAYMENT_RECEIPT', 'Payment receipt'), ('STOCK_ADJUSTMENT', 'Stock adjustment'), ('OPENING_BALANCE', 'Opening balance (data migration)')], max_length=20)),
                ('reference', models.CharField(blank=True, help_text='PO/SO/Voucher/Claim number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PartyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('party', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='_balance_cache', to='accounting.party')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_number', models.CharField(max_length=30, unique=True)),
                ('voucher_type', models.CharField(choices=[('PAYMENT', 'Payment voucher'), ('JOURNAL', 'Journal voucher'), ('EXPENSE', 'Expense voucher')], max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('narration', models.CharField(blank=True, max_length=255)),
                ('payment_mode', models.CharField(blank=True, choices=[('CASH', 'Cash'), ('BANK', 'Bank')], help_text='Payment/Expense vouchers only.', max_length=10)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment/Expense vouchers: the single amount moved. Journal vouchers use the line items instead.', max_digits=14, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('debit_account', models.ForeignKey(blank=True, help_text='Payment: the payable/expense account being debited. Expense: the expense account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher', to='accounting.journalentry')),
                ('party', models.ForeignKey(blank=True, help_text='Payment voucher: who the payment is to/from.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounting.party')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.chartofaccount')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='accounting.party')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.voucher')),
            ],
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.chartofaccount')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines', to='accounting.party')),
            ],
            options={
                'indexes': [models.Index(fields=['account'], name='accounting__account_c6b1e8_idx'), models.Index(fields=['party'], name='accounting__party_i_2af6e5_idx')],
            },
        ),
    ]
