# Generated by Django 5.2.17 on 2026-09-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_journalentry_partybalance_voucher_voucherline_and_more'),
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='party',
            field=models.OneToOneField(blank=True, help_text='Accounting party this shop posts its receivable ledger against (Accounts #5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='accounting.party'),
        ),
    ]
