# Generated by Django 5.2.17 on 2026-09-16 11:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_head_office', models.BooleanField(default=False)),
                ('requires_po_approval', models.BooleanField(default=False, help_text='Out-station branches (e.g. Bhera, Bhalwal) require internal PO approval before submission to PTC.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('PURCHASE_IN', 'Purchase received'), ('PURCHASE_RETURN_OUT', 'Purchase return claimed back to PTC'), ('SALE_OUT', 'Sale dispatched'), ('SALE_RETURN_IN', 'Sale return received'), ('TRANSFER_OUT', 'Transferred out to another warehouse'), ('TRANSFER_IN', 'Transferred in from another warehouse'), ('ADJUSTMENT', 'Adjustment (damage / loss / stolen / stock count)'), ('OPENING_BALANCE', 'Opening balance (data migration)')], max_length=20)),
                ('quantity_change', models.DecimalField(decimal_places=3, help_text='Signed quantity in sticks... or whatever base unit the SKU is tracked in. Positive = stock increase.', max_digits=14)),
                ('reference', models.CharField(blank=True, help_text='PO/SO/Transfer/Claim number', max_length=100)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('IN_TRANSIT', 'In transit'), ('RECEIVED', 'Received'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.warehouse')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.sku')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='warehouses.stocktransfer')),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('DAMAGE', 'Damaged'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('COUNT_CORRECTION', 'Physical count correction')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Enter as a positive number; it is applied as a stock decrease unless it is a positive count correction.', max_digits=14)),
                ('is_increase', models.BooleanField(default=False, help_text='Tick only for a physical count correction that found MORE stock than recorded.')),
                ('ptc_claim_reference', models.CharField(blank=True, max_length=50)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='catalog.sku')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment', to='warehouses.stockledgerentry')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='warehouses.warehouse')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyStockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimum_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_levels', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_stock_levels', to='warehouses.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='catalog.sku')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='warehouses.warehouse')),
            ],
            options={
                'unique_together': {('warehouse', 'sku')},
            },
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['warehouse', 'sku'], name='warehouses__warehou_b622c2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledgerentry',
            index=models.Index(fields=['entry_type'], name='warehouses__entry_t_c71cd6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='safetystocklevel',
            unique_together={('warehouse', 'sku')},
        ),
    ]
