# Generated by Django 5.2.17 on 2026-09-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledgerentry',
            name='batch_number',
            field=models.CharField(blank=True, help_text='Batch/lot number, e.g. moisture-sensitive stock — mandatory tracking for VELO (questionnaire #18).', max_length=50),
        ),
        migrations.AddField(
            model_name='stockledgerentry',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Batch expiry date, e.g. for VELO (questionnaire #18). Optional for SKUs that do not need it.', null=True),
        ),
    ]
